spring:
  shell:
    interactive:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    #    generate-ddl: true
    hibernate:
      ddl-auto: none
    #      ddl-auto: create-drop

    show-sql: true

    liquibase:
      enabled: true

#logging:
#  level:
#    root: DEBUG

